# Generated by Django 3.2.5 on 2022-04-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesAdditionFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('ClassID', models.ForeignKey(db_constraint=False, default='deleted_class', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.classes')),
            ],
        ),
    ]
