# Generated by Django 3.2.5 on 2022-04-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220423_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesadditionfunction',
            name='ClassID',
            field=models.OneToOneField(db_constraint=False, default='deleted_class', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='app.classes'),
        ),
    ]
